### ISSUE TITLE
[Tx-builder] Safari does not retain saved transaction library

### ISSUE THREAD

**Issue by ShardYaco** [safe-global/safe-react-apps#538]
## Environment
 - Browser: Safari Version 16.0 (17614.1.25.9.10, 17614)
 - Wallet: WalletConnect
 - Safe: eth:0x87D93d9B2C672bf9c9642d853a8682546a5012B5
 - Environment:
   - production (Ethereum Mainnet)

## Steps to reproduce
 1. Open Safari on MacOS
 2. Visit https://gnosis-safe.io/
 3. Open Tx Builder
 4. Build the multistep tx and save it to the local storage
 5. Execute (optional, I guess)

## Expected result
The transaction should be retained in the library as long as I don't clear my local storage.

## Obtained result
The transaction disappears after some time.

**Comment by mikhailxyz** [comment]
I could not fully break down the issue because of problems with Safari, but I'll share what I found.

**I was able to reproduce the issue by doing the following:**
1. Open transaction builder Safe App
2. Create a transaction and save it to the library
3. After refreshing, the transaction was still there for me (although I had a couple of refreshes that removed the transaction 🤔)
4. If I close Safari and navigate to the Transaction Builder Safe App, the transaction is not there <-- **This I could reproduce constantly*


- We use `localForage` for storing transactions in the browser, which uses IndexedDB and WebSQL and falls back to localStorage where the former isn't supported
- After saving a transaction to the library in Safe, Safari doesn't show anything in the IndexedDB through the inspector, although the transaction can be seen in the library in the app
<img width="1714" alt="Screenshot 2022-10-12 at 16 49 00" src="https://user-images.githubusercontent.com/16622558/195377017-0747230e-d552-420b-bedb-7a01dd350b8e.png">
Screenshot of indexedDB from Chrome after performing the same steps:
<img width="1917" alt="Screenshot 2022-10-12 at 16 56 48" src="https://user-images.githubusercontent.com/16622558/195377369-8e9f735a-fd21-4465-a129-f9eac6b4cb84.png">

- I would assume that Safari is enforcing some particular behaviour to (cross-origin) iframes and IndexedDB. I found some reports of a similar issue and all other kinds of problems with IndexedDB/Storage in Safari, although in our case, we don't have any console errors:
https://stackoverflow.com/questions/61596671/can-indexeddb-work-inside-an-iframe-in-safari
https://twitter.com/feross/status/1404568122158313474
https://stackoverflow.com/questions/38584273/local-storage-cross-domain-safari-disables-it-by-default

**Solution**:
Although it doesn't make a lot of sense, I was able to "fix" the issue by disabling the prevention of cross-site tracking in Safari's privacy settings:
<img width="904" alt="Screenshot 2022-10-12 at 17 05 11" src="https://user-images.githubusercontent.com/16622558/195379425-5e60ced3-1d35-4723-9540-5d9f463cd739.png">
I suggest trying this and seeing if it fixes the problem for you, although a better long-term solution would be to use a different browser.

Questions: 
- Apparently, IndexedDB is disabled in cross-origin iframes in Safari - how does the tx library work then? https://bugzilla.mozilla.org/show_bug.cgi?id=595307
