### ISSUE TITLE
internal safe apps recognised as MultiSend

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#638]
## Description

Internal safe apps like the tx-builder or drain account are not recognised as internal safe apps on the tx queue and history tabs. I was able to reproduce this in Polygon, Optimism and Gnosis Chain

## Steps to reproduce
Go to either app and perform a dummy transaction.

## Obtained result

Optimism:
<img width="966" alt="Screenshot 2022-12-29 at 09 26 47" src="https://user-images.githubusercontent.com/92332710/209925463-a3238be1-7f8e-47b0-b411-51d48ce29c8b.png">

Gnosis Chain:
<img width="965" alt="Screenshot 2022-12-29 at 09 39 11" src="https://user-images.githubusercontent.com/92332710/209925821-2f4dd8fe-7c92-463a-8462-b86aa8c129e6.png">

## Expected result
App info is displayed

**Comment by yagopv** [comment]
Solving [this](https://github.com/safe-global/web-core/issues/1563) fixes partially this issue

**Comment by yagopv** [comment]
@JagoFigueroa the fix for 1 owner Safes is in the release branch so you can test the whole problem is fixed finally

We need to test:

1 Owner Safes => Fixed in the [1.4.0 release candidate](https://github.com/safe-global/web-core/pull/1599)
Multi Owner Safes => [Fixed](https://github.com/safe-global/safe-transaction-service/releases/tag/v4.14.0) and deployed in production

**Comment by JagoFigueroa** [comment]
Looking good to me, checked these 2 scenarios on a few chains on the RC + prod and I can see our apps info 😄
