### ISSUE TITLE
[Tx-builder] Unable to download tx batches on Firefox & Safari browsers

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-react-apps#660]
## Description
Batch download action is not working correctly on these browsers.

Browsers tested: Chrome, Brave, Firefox, Safari & Edge

## Steps to reproduce
On either safari or firefox browsers, go to tx-builder safe app, create a dummy batch and try to download it

## Expected result
.json file downloaded as expected 

## Obtained result
<img width="1725" alt="Screenshot 2023-02-02 at 12 43 34" src="https://user-images.githubusercontent.com/92332710/216316116-4d68f649-680a-445a-b09f-3f1fb75e9278.png">

**Comment by DiogoSoaress** [comment]
Hey @JagoFigueroa , I was checking this bug in the scope of https://github.com/safe-global/safe-react-apps/pull/698 and it seems to due to a missing CSP header -> https://bugzilla.mozilla.org/show_bug.cgi?id=1365502 . this is the intended behavior and a way to circumvent it would be to add `blob:` in the `frame-src` response header as per suggested in https://stackoverflow.com/a/66902961/7365255 . This would be done on the infra side tho.
