### ISSUE TITLE
[Wallet Connect] Check WalletConnect v2 is using latest SDK version

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-react-apps#705]
## Description
28th of June Wallet Connect will be shutting down v1. As we created our implementation some time ago we need to ensure we are compatible with all scenarios when using v2. This was a bit more difficult to test before as there were very few or none apps appart from the demo applications.

## Links
[Wallet Connect v2 original ticket](https://github.com/safe-global/safe-react-apps/issues/178)
[Wallet Connect v2 implementation PR, with testing examples](https://github.com/safe-global/safe-react-apps/pull/563)

**Comment by Sparragus** [comment]
I know this isn't the best place to reach out, but since you're doing a QA pass on the WalletConnect v2 implementation, I thought it'd be worthwhile sharing the issue here, too.

I found an issue with the declared namespace in the wc v2 session. Hi everyone. I documented it here: https://github.com/safe-global/safe-react-apps/issues/709

I'll be happy to discuss it and help as needed.
